CREATE TABLE employees (
  employee_uid VARCHAR(36) NOT NULL,
  employee_id VARCHAR(50) NOT NULL,
  first_name_th VARCHAR(100) NOT NULL,
  last_name_th VARCHAR(100) NOT NULL,
  first_name_en VARCHAR(100) DEFAULT NULL,
  last_name_en VARCHAR(100) DEFAULT NULL,
  email VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) DEFAULT NULL,
  last_login DATETIME DEFAULT NULL,
  login_attempts INT(11) DEFAULT NULL,
  locked_until DATETIME DEFAULT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  department VARCHAR(100) NOT NULL,
  position VARCHAR(100) DEFAULT NULL,
  employee_type ENUM('university', 'department', 'contract') NOT NULL,
  hire_date DATE DEFAULT NULL,
  status ENUM('active', 'inactive', 'resigned') NOT NULL,
  role ENUM('admin', 'manager', 'user') DEFAULT NULL,
  created_at DATETIME NOT NULL,
  updated_at DATETIME NOT NULL,
  PRIMARY KEY (employee_uid),
  UNIQUE KEY uk_employees_employee_id (employee_id),
  UNIQUE KEY uk_employees_email (email),
  KEY idx_employees_department (department),
  KEY idx_employees_employee_type (employee_type),
  KEY idx_employees_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
